name: base
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb18efdd_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h1c322ee_7
  - brotli-bin=1.0.9=h1c322ee_7
  - brotlipy=0.7.0=py39hb18efdd_1004
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - ccache=4.7.1=hef5e26d_0
  - cctools=973.0.1=h43ef6ec_10
  - cctools_osx-arm64=973.0.1=h8e51184_10
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py39h7e6b969_1
  - chardet=5.0.0=py39h2804cbe_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py39h2804cbe_0
  - cmake=3.24.2=h967666c_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=22.9.0=py39h2804cbe_1
  - conda-build=3.21.9=py39h2804cbe_1
  - conda-package-handling=1.9.0=py39h02fc5c5_0
  - cryptography=38.0.2=py39he2a39a8_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.3=py39h3c22d25_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.0.0rc9=pyhd8ed1ab_0
  - executing=1.1.1=pyhd8ed1ab_0
  - expat=2.4.9=hb7217d7_0
  - expecttest=0.1.4=pyhd8ed1ab_0
  - filelock=3.8.0=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.38.0=py39h02fc5c5_0
  - freetype=2.12.1=hd633e50_0
  - future=0.18.2=py39h2804cbe_5
  - glob2=0.7=py_0
  - hypothesis=6.56.3=py39h2804cbe_0
  - icu=70.1=h6b3803e_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39h2804cbe_0
  - importlib_resources=5.10.0=pyhd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.16.1=pyh736e0ef_0
  - ipython=8.5.0=pyhd1c38e8_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.2=pyhd8ed1ab_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=he4db4b2_2
  - jsonschema=4.16.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py39h2804cbe_7
  - jupyter_client=7.4.3=pyhd8ed1ab_0
  - jupyter_console=6.4.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39h2804cbe_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.3=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py39hab5e169_0
  - krb5=1.19.3=he492e65_0
  - lcms2=2.12=had6a04f_0
  - ld64=609=h954701c_10
  - ld64_osx-arm64=609=h6ce2ded_10
  - lerc=4.0.0=h9a09cb3_0
  - libarchive=3.5.2=hdd7f49f_3
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1c322ee_7
  - libbrotlidec=1.0.9=h1c322ee_7
  - libbrotlienc=1.0.9=h1c322ee_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.85.0=h1c293e1_0
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - libhiredis=1.0.2=hbec66e7_0
  - libiconv=1.17=he4db4b2_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblief=0.12.2=hb7217d7_0
  - libllvm13=13.0.1=hfd59cb2_2
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.38=h76d750c_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.39.4=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtiff=4.4.0=hfa0b094_4
  - libuv=1.44.2=he4db4b2_0
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=14.0.4=hd125106_0
  - lz4-c=1.9.3=hbdafb3b_1
  - lzo=2.10=h642e427_1000
  - markupsafe=2.1.1=py39hb18efdd_1
  - matplotlib=3.5.2=py39hdf13c20_0
  - matplotlib-base=3.5.2=py39h4ee150f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py39h5161555_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy=0.982=py39h02fc5c5_0
  - mypy_extensions=0.4.3=py39h2804cbe_5
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.5=py39h2804cbe_0
  - nbformat=5.7.0=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.4.12=pyha770c72_0
  - numpy=1.23.4=py39hefdcf20_0
  - openjpeg=2.5.0=h5d4e404_1
  - openssl=3.0.5=h03a7124_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patch=2.7.6=h27ca646_1002
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39he45c975_2
  - pkginfo=1.8.3=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - pluggy=1.0.0=py39h2804cbe_3
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - prompt_toolkit=3.0.31=hd8ed1ab_0
  - psutil=5.9.3=py39h02fc5c5_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-lief=0.12.2=py39h23fbdae_0
  - pycosat=0.6.3=py39hb18efdd_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py39hb18efdd_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.1.3=py39h2804cbe_0
  - python=3.9.13=h96fcbfb_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python-libarchive-c=4.0=py39h2804cbe_1
  - python_abi=3.9=2_cp39
  - pytz=2022.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb18efdd_4
  - pyzmq=24.0.1=py39h0553236_0
  - readline=8.1.2=h46ed386_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rhash=1.4.3=he4db4b2_0
  - ripgrep=13.0.0=h65448a5_2
  - ruamel_yaml=0.15.80=py39h9eb174b_1007
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.39.4=h2229b38_0
  - stack_data=0.5.1=pyhd8ed1ab_0
  - tapi=1100.0.11=he4954df_0
  - terminado=0.16.0=pyhd1c38e8_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py39h9eb174b_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.5.0=pyhd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022e=h191b570_0
  - unicodedata2=14.0.0=py39hb18efdd_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.9.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
    - distlib==0.3.6
    - mpmath==1.2.1
    - networkx==3.0b1
    - ninja==1.10.2.4
    - pbr==5.11.0
    - pip==22.1.2
    - platformdirs==2.5.3
    - stevedore==4.1.1
    - sympy==1.11.1
    - virtualenv==20.16.6
    - virtualenv-clone==0.5.7
    - virtualenvwrapper==4.8.4
prefix: /Users/rishubtamirisa/miniforge3
